Closing mongoose connection after tests are finished.
Motivation:
Currently I'm seeing the following error when running all the test:
$ grunt fh:unit
...
    1) "before all" hook for "it_should_removeAppCollection"

  82 passing (12s)
  1 failing

  1) middleware/appdata "before all" hook for
"it_should_removeAppCollection":
     TypeError: Cannot read property 'connection' of undefined
      at node_modules/mockgoose/Mockgoose.js:113:50
      at NativeConnection.Connection.error
(node_modules/mongoose/lib/connection.js:388:24)
      at NativeConnection.Connection.open
(node_modules/mongoose/lib/connection.js:212:10)
      at Mongoose.connect (node_modules/mongoose/lib/index.js:212:15)
      at Mongoose.mongoose.connect
(node_modules/mockgoose/Mockgoose.js:111:51)
      at Context.exports.middleware/appdata.before
(test/unit/middleware/test_appdata.js:33:14)

Following this issue into node_modules/mockgoose/Mockgoose.js I could
see the following error.
{ [Error: Trying to open unclosed connection.] state: 1 }

It looks like there are some test that are not closing the connection
after they are done it it.

Modifications:
Adding close calls so that the mongoose connections are closed after the
tests are run.

Result:
The test pass when running:
$ grunt fh:unit