Moving the setup on fhConfig to a setUp method.
Motivation:
Currently when running the unit test using 'grunt fh:unit' the tests
fail. The error reported is:
1 failing

  1)  test_call_stats:
     TypeError: Cannot read property 'protocol' of undefined
      at callStats (lib/handlers/stats/stats_client.js:7:30)
      at Context.exports.test_call_stats
(test/unit/handlers/stats/test_stats.js:50:3)

Running this test individually passes. I seems that the test
test/unit/models/test-appmbaas.js is setting this global configuration
but not resetting it afterwards causing issues for the test_stats test.

Modifications:
Moved the configuration of fhConfig in test_stats.js to a setUp method
to avoid the issue reported.

Result:
All unit and coverage targets pass:
$ grunt fh:unit
$ grunt fh:coverage

JIRA:
https://issues.jboss.org/browse/RHMAP-5369